image: Visual Studio 2013

branches:
  only:
    - master

platform: x64
configuration: Release

cache:
    - '%CYG_CACHE%'

environment:
  CYG_PACKAGES: make,zip,unzip
  CYG_MIRROR: http://cygwin.mirror.constant.com
  CYG_ROOT: C:/cygwin64
  CYG_CACHE: C:/cygwin64/var/cache/setup
  CYG_SETUP: C:/cygwin64/setup-x86_64.exe

init:
    - git config --global core.autocrlf input

install:
  - if defined CYG_ROOT (%CYG_SETUP% --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages "%CYG_PACKAGES%" --upgrade-also)

build_script:
  - curl -OL https://ci.appveyor.com/api/buildjobs/l1aoprlilqmsd2wx/artifacts/freetype_2.8.1_x86_windows_dll.zip
  - 7z x freetype_2.8.1_x86_windows_dll.zip -ofreetype
  - copy freetype\lib\freetype.lib freetype\bin\freetype.lib
  - git clone https://github.com/corretto/corretto-8.git
  - '%CYG_ROOT%/bin/bash -lc "bash /cygdrive/c/projects/compact-profiles/corretto-8/src/configure --with-debug-level=release --disable-debug-symbols --disable-zip-debug-info --with-target-bits=64 --enable-unlimited-crypto --with-freetype-include=/cygdrive/c/projects/freetype/include --with-freetype-lib=/cygdrive/c/projects/freetype/bin'
  - '%CYG_ROOT%/bin/bash -lc "cd /cygdrive/c/projects/compact-profiles/corretto-8/src && make profiles'
